### ISSUE TITLE
randomly got an critical error

### ISSUE THREAD

**Issue by simpzan** [zhuhaow/NEKit#16] opened 2016-09-11 03:25 UTC
```
<Critical>: NWTCPSocket got an error when reading data: Optional(Error Domain=NSPOSIXErrorDomain Code=57 "Socket is not connected")
```

**Comment by zhuhaow** [comment] 2016-09-11 03:31
This is by design. I may remove that log soon.

-------------------
Zhuhao Wang
Zhejiang university

2016年9月11日 +0800 11:25 Samuel <notifications@github.com>，写道：

**Comment by simpzan** [comment] 2016-09-11 05:33
If this is a normal case, It should not be an critical error.

**Comment by zhuhaow** [comment] 2016-09-11 05:36
I agree.
It is the system that thinks it is critical. However, there is no consequence. This error is there because I want to simplify the implementations. Will be fixed.

-------------------
Zhuhao Wang
Zhejiang university

2016年9月11日 +0800 13:33 Samuel <notifications@github.com>，写道：

**Closed** 2016-12-10 02:55 UTC
Labels: enhancement
